export const PRODUIT_LIST_REQUEST = 'PRODUIT_LIST_REQUEST';
export const PRODUIT_LIST_SUCCESS = 'PRODUIT_LIST_SUCCESS';
export const PRODUIT_LIST_FAIL = 'PRODUIT_LIST_FAIL';

export const PRODUIT_DETAILS_REQUEST = 'PRODUIT_DETAILS_REQUEST';
export const PRODUIT_DETAILS_SUCCESS = 'PRODUIT_DETAILS_SUCCESS';
export const PRODUIT_DETAILS_FAIL = 'PRODUIT_DETAILS_FAIL';

export const PRODUIT_SAVE_FAIL = 'PRODUIT_SAVE_FAIL';
export const PRODUIT_SAVE_SUCCESS = 'PRODUIT_SAVE_SUCCESS';
export const PRODUIT_SAVE_REQUEST = 'PRODUIT_SAVE_REQUEST'


export const PRODUIT_DELETE_FAIL = 'PRODUIT_DELETE_FAIL';
export const PRODUIT_DELETE_SUCCESS = 'PRODUIT_DELETE_SUCCESS';
export const PRODUIT_DELETE_REQUEST = 'PRODUIT_DELETE_REQUEST'
